Repository Myth-64/SELab_Mini_Project, pull requests merged in 2024-03, with the labels that each got.

#29 Added Unit testcases for UserRestController and PaperRestController
  .github/workflows/maven-build.yml
  .github/workflows/maven-publish.yml
  backend/pom.xml
  backend/src/main/java/com/example/demo/Dao/AuthRequest.java
  backend/src/main/java/com/example/demo/controller/LoginController.java
  backend/src/main/java/com/example/demo/filter/JwtAuthFilter.java
  backend/src/main/java/com/example/demo/model/Role.java
  backend/src/main/java/com/example/demo/model/User.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
  backend/src/main/java/com/example/demo/restController/UserRestController.java
  backend/src/main/java/com/example/demo/service/UserInfoUserDetails.java
  backend/src/main/java/com/example/demo/service/UserInfoUserDetailsService.java
  backend/src/main/resources/static/open-api.json
  backend/src/test/java/com/example/demo/PaperRestControllerTest.java
  backend/src/test/java/com/example/demo/SeLabMiniProjectApplicationTests.java
  backend/src/test/java/com/example/demo/UserRestControllerTest.java
Labels: testcases

#30 Added API endpoint for frequency map of papers by their status
  backend/src/main/java/com/example/demo/repository/PaperRepository.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
  backend/src/main/java/com/example/demo/restController/ReviewRestController.java
  backend/src/main/java/com/example/demo/sqlQueryClasses/PaperStatusCountMap.java
  client/src/pages/Home.jsx
Labels: enhancement

#31 Reviewer page initial version
  client/src/assets/styles/PaperDetails.css
  client/src/assets/styles/Paperinfo.css
  client/src/pages/AssignReviewers.jsx
  client/src/pages/Home.jsx
  client/src/pages/PaperDetail.jsx
  client/src/pages/PaperInfo.jsx
Labels: feature

#33 added review modal and correct api endpoints in frontend
  backend/src/main/java/com/example/demo/restController/ReviewRestController.java
  backend/src/main/java/com/example/demo/security/SecurityConfiguration.java
  backend/src/main/resources/data-init.sql
  client/src/App.css
  client/src/App.jsx
  client/src/assets/styles/AssignModal.css
  client/src/assets/styles/PaperDetails.css
  client/src/assets/styles/Paperinfo.css
  client/src/assets/styles/SideBar.css
  client/src/assets/styles/UserListItem.css
  client/src/auth/PrivateRoutes.jsx
  client/src/components/AssignModal.jsx
  client/src/components/UserBadge.jsx
  client/src/components/UserListItem.jsx
  client/src/pages/AssignReviewers.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/Home.jsx
  client/src/pages/PaperDetail.jsx
  client/src/pages/PaperInfo.jsx
Labels: feature

#36 Add reviewers feature
  backend/src/main/java/com/example/demo/repository/PaperRepository.java
  backend/src/main/java/com/example/demo/repository/ReviewRepository.java
  backend/src/main/java/com/example/demo/requestClasses/AddReviewerRequest.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
  backend/src/main/resources/application-init.properties
  backend/src/main/resources/application.properties
  client/src/App.css
  client/src/assets/styles/PaperDetails.css
  client/src/assets/styles/Paperinfo.css
  client/src/pages/Home.jsx
  client/src/pages/PaperInfo.jsx
Labels: enhancement, feature

#38 Added service for sending mail
  backend/pom.xml
  backend/src/main/java/com/example/demo/requestClasses/StatusChangePaperId.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
  backend/src/main/java/com/example/demo/service/EmailService.java
  backend/src/main/resources/application.properties
Labels: feature

#39 Added endpoints for accepting and rejecting papers
  backend/src/main/java/com/example/demo/repository/PaperRepository.java
  backend/src/main/java/com/example/demo/requestClasses/StatusChangePaperId.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
Labels: feature

#40 Added endpoint for showing only completed reviews
  backend/src/main/java/com/example/demo/repository/ReviewRepository.java
  backend/src/main/java/com/example/demo/restController/ReviewRestController.java
  client/src/pages/PaperDetail.jsx
Labels: enhancement

#41 Added feature to notify reviewers
  backend/src/main/java/com/example/demo/requestClasses/PaperIdRequest.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data-init.sql
  backend/src/main/resources/static/open-api.json
  backend/src/main/resources/static/swagger.yaml
Labels: documentation, feature

#42 Fixed bug in findByPaperCompleted
  backend/src/main/java/com/example/demo/repository/ReviewRepository.java
  backend/src/main/java/com/example/demo/restController/PaperRestController.java
Labels: bug
